---
- name: Configure Load Balancer
  hosts: loadbalancer
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/secret-vars.yml
  tasks:

    - name: Update and Upgrade System Packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Snap (Required for Certbot)
      apt:
        name: snapd
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx for Load Balancing
      copy:
        dest: "/etc/nginx/sites-available/tems_loadbalancer"
        content: |
          upstream tems_backend {
              server "{{ web_server_1 }}:5000";
              server "{{ web_server_2 }}:5000";
          }
          server {
              listen 80;
              server_name "{{ load_balancer_ip }}";
              location / {
                  proxy_pass http://tems_backend;
              }
          }
    - name: Enable Load Balancer
      file:
        src: /etc/nginx/sites-available/tems_loadbalancer
        dest: /etc/nginx/sites-enabled/tems_loadbalancer
        state: link


    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
