---
- name: Secure Load Balancer with HTTPS
  hosts: loadbalancer
  become: true
  vars_files:
    - vars/vars.yml
    - vars/secret-vars.yml
  tasks:
    - name: Update and Upgrade System Packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Certbot using Snap (avoiding APT issues)
      command: snap install --classic certbot
      args:
        creates: /snap/bin/certbot

    - name: Ensure Certbot is in PATH
      command: ln -s /snap/bin/certbot /usr/bin/certbot
      args:
        creates: /usr/bin/certbot

    - name: Obtain SSL Certificate using Load Balancer IP
      command: certbot --nginx -d {{ load_balancer_ip }} --non-interactive --agree-tos -m admin@yourdomain.com
      args:
        creates: /etc/letsencrypt/live/{{ load_balancer_ip }}/fullchain.pem

    - name: Setup Auto-Renewal for SSL
      cron:
        name: "Renew SSL Certificate"
        job: "certbot renew --quiet"
        special_time: weekly
