---
- name: Configure Logwatch
  hosts: loadbalancer
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/secret-vars.yml
  tasks:
    - name: Install Logwatch
      apt:
        name: logwatch
        state: present

    - name: Copy logwatch.conf
      copy:
        src: ../files/logwatch.conf
        dest: /etc/logwatch/conf/logwatch.conf
        owner: root
        group: root
        mode: '0644'
