---
- name: Secure Load Balancer with HTTPS
  hosts: loadbalancer
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/secret-vars.yml

  tasks:
    - name: Install Snapd
      apt:
        name: snapd
        state: present

    - name: Install Certbot using Snap
      command: snap install --classic certbot
      args:
        creates: /snap/bin/certbot

    - name: Ensure Certbot in PATH
      file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
      ignore_errors: true

    - name: Obtain SSL Certificate
      command: >
        certbot --nginx
        -d {{ lb_domain_name }}
        --non-interactive
        --agree-tos
        -m admin@{{ lb_domain_name }}
      args:
        creates: "/etc/letsencrypt/live/{{ lb_domain_name }}/fullchain.pem"

    - name: Setup Auto-Renewal
      cron:
        name: Renew SSL Cert
        job: "certbot renew --quiet"
        special_time: weekly
