
---
- name: Secure Load Balancer with HTTPS
  hosts: loadbalancer
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/secret-vars.yml

  tasks:
    - name: Update and Upgrade System Packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Certbot and Nginx plugin via APT
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Obtain SSL Certificate using Certbot
      command: >
        certbot --nginx -d {{ lb_domain_name }}
        --non-interactive --agree-tos -m admin@{{ lb_domain_name }}
      args:
        creates: "/etc/letsencrypt/live/{{ lb_domain_name }}/fullchain.pem"

    - name: Setup Auto-Renewal for SSL
      cron:
        name: "Renew SSL Certificate"
        job: "certbot renew --quiet"
        special_time: weekly
