---
- name: Install and Configure Web Servers (Gunicorn for Flask)
  hosts: 10.2.37.62
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/secret-vars.yml

  tasks:
    - name: Update and Upgrade System Packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - python3-pip
          - python3-venv
          - nginx   # If needed locally, but the LB is also running Nginx
        state: present

    - name: Create /var/www/tems directory
      file:
        path: /var/www/tems
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create Python virtual environment
      command: python3 -m venv /var/www/tems/venv
      args:
        creates: /var/www/tems/venv

    - name: Copy requirements.txt
      copy:
        src: ../files/requirements.txt
        dest: /var/www/tems/requirements.txt

    - name: Install Python packages
      pip:
        requirements: /var/www/tems/requirements.txt
        virtualenv: /var/www/tems/venv

    - name: Copy Flask app (app.py)
      copy:
        src: ../files/app.py
        dest: /var/www/tems/app.py
        mode: '0755'

    - name: Copy HTML templates
      copy:
        src: ../files/templates/
        dest: /var/www/tems/templates/
        mode: '0755'
      with_fileglob:
        - "*.html"
      loop_control:
        label: "{{ item }}"

    - name: Copy static files
      copy:
        src: ../files/static/
        dest: /var/www/tems/static/
        mode: '0755'
      with_fileglob:
        - "*.css"
      loop_control:
        label: "{{ item }}"

    - name: Copy .env
      copy:
        src: ../files/env.txt
        dest: /var/www/tems/.env
        mode: '0600'

    - name: Create systemd service for TEMS (Gunicorn)
      copy:
        dest: /etc/systemd/system/tems_app.service
        content: |
          [Unit]
          Description=TEMS Flask App
          After=network.target

          [Service]
          User=root
          Group=root
          WorkingDirectory=/var/www/tems
          EnvironmentFile=/var/www/tems/.env
          ExecStart=/var/www/tems/venv/bin/gunicorn --bind 0.0.0.0:5000 app:app
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Restart TEMS

  handlers:
    - name: Restart TEMS
      systemd:
        name: tems_app
        state: restarted
        enabled: yes
