---
- name: Install and Configure MinIO Storage
  hosts: storageservers
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/secret-vars.yml
  tasks:
    - name: Update and Upgrade System Packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Download MinIO Binary
      get_url:
        url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
        dest: "/usr/local/bin/minio"
        mode: '0755'

    - name: Create MinIO Data Directory
      file:
        path: "{{ minio_data_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create MinIO systemd service
      copy:
        dest: "/etc/systemd/system/minio.service"
        content: |
          [Unit]
          Description=MinIO Storage Service
          After=network.target

          [Service]
          User=root
          Group=root
          Environment="MINIO_ROOT_USER={{ minio_root_user }}"
          Environment="MINIO_ROOT_PASSWORD={{ minio_root_password }}"
          ExecStart=/usr/local/bin/minio server {{ minio_data_dir }} --console-address ":{{ minio_console_port }}"
          Restart=always
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start and Enable MinIO
      systemd:
        name: minio
        state: started
        enabled: yes
