---
- name: Configure Load Balancer
  hosts: loadbalancer
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/secret-vars.yml
  tasks:
    - name: Update and Upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Deploy Nginx config template
      template:
        src: ../files/nginx_config.j2
        dest: /etc/nginx/sites-available/tems.conf
      notify: Reload Nginx

    - name: Enable tems site
      file:
        src: /etc/nginx/sites-available/tems.conf
        dest: /etc/nginx/sites-enabled/tems.conf
        state: link
      notify: Reload Nginx

    - name: Remove default site if present
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
